# Generated by Django 4.0 on 2021-12-17 23:12

from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1024, verbose_name='Nombre Punto')),
                ('direccion', models.CharField(max_length=1024, verbose_name='Direccion Punto')),
                ('geo_ubicacion', djgeojson.fields.PointField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgendaTelefonica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PBX', 'Numero PBX con indicativo'), ('Fijo', 'Numero fijo'), ('Celular', 'Numero celular')], default='Fijo', max_length=10)),
                ('numero', models.CharField(max_length=20, verbose_name='Numero Contacto')),
                ('punto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='puntos.punto')),
            ],
        ),
    ]
