# Generated by Django 4.0 on 2021-12-17 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1024, verbose_name='Nombre Empleado')),
                ('apellido', models.CharField(max_length=1024, verbose_name='Nombre Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaTelefonica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Fijo', 'Numero fijo'), ('Celular', 'Numero celular')], default='Fijo', max_length=10)),
                ('numero', models.CharField(max_length=20, verbose_name='Numero Contacto')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
        ),
    ]
