# Generated by Django 4.0 on 2021-12-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llamadas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrollamada',
            name='quien_contesta',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrollamada',
            name='estado',
            field=models.CharField(choices=[('Sin Contestar', 'Sin Contestar'), ('Contestado', 'Contestado'), ('Llamando', 'Llamando')], default='Contestado', max_length=20),
        ),
    ]
