# Generated by Django 4.0 on 2021-12-22 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llamadas', '0002_registrollamada_quien_contesta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrollamada',
            old_name='quien_contesta',
            new_name='persona_contesta',
        ),
    ]
